### PR TITLE
Add recipe on setting system headers paths

### PR DESCRIPTION
**Pull request by piotrsiupa**
It adds recipe "Search a custom directory for system .h files" to make a custom tool which creates a construction variable `CPPSYSPATH`.

### CODE REVIEW

**Comment by mwichmann** [comment]
I think this would be a useful addition. We'll see what @bdbaddog thinks.

**Comment by bdbaddog** [comment]
Can you add more explanation at the top of the page what it's doing, why you'd want to do this, also what's the downside of doing this? (paths no searched)..

This might be better as a scons-contrib rather than a cookbook item.

**Comment by bdbaddog** [comment]
The difference being cookbook = recommended practice
scons-contrib - here's some logic to do something you might find useful, but may not be mainstream enough to be packaged with SCons itself.

**Comment by bdbaddog** [comment]
If you had the normal CPPPATH expansion skip any paths which were in CPPSYSPATH, then you'd still get the files scanned and have them cause rebuilds, and get some of them with -isystem..

**Comment by piotrsiupa** [comment]
> Can you add more explanation at the top of the page what it's doing, why you'd want to do this, also what's the downside of doing this? (paths no searched)..
> 
> This might be better as a scons-contrib rather than a cookbook item.

I'm not aware of any problems with this. If you can suggest something, I'll add it.
Although, I'm leaning towards adding it to the scons-contrib. You're right that it fits there more since it's a complete stand-alone tool and not just a code snippet.

> The difference being cookbook = recommended practice scons-contrib - here's some logic to do something you might find useful, but may not be mainstream enough to be packaged with SCons itself.

I would debate on whether having some external library that should be treated as a system header is not mainstream but OK.

**Comment by piotrsiupa** [comment]
> If you had the normal CPPPATH expansion skip any paths which were in CPPSYSPATH, then you'd still get the files scanned and have them cause rebuilds, and get some of them with -isystem..

I'm not sure if I get the context of this statement. I've tested what happens if you just add `-isystem` without including the directory to `CPPPATH` it the headers are not in the dependency tree in this case.

**Comment by bdbaddog** [comment]
Since your implementation breaks file scanning for the system paths I would
want to recommend it in its current form.
Not saying there’s no value in this functionality

**Comment by piotrsiupa** [comment]
@bdbaddog Could you elaborate? How does it break file scanning? Should it not scan system paths?

**Comment by bdbaddog** [comment]
> > If you had the normal CPPPATH expansion skip any paths which were in CPPSYSPATH, then you'd still get the files scanned and have them cause rebuilds, and get some of them with -isystem..
> 
> I'm not sure if I get the context of this statement. I've tested what happens if you just add `-isystem` without including the directory to `CPPPATH` and my observation is that the headers are not in the dependency tree in this case.

Yes. That's the problem.  
As I understand it you'd add paths via -isystem to avoid the compiler complaining about them, but you do want to know if those files change and that should cause a rebuild.

**Comment by bdbaddog** [comment]
Also you'd want to have the build do something reasonable (like use -I if no equivalent -isystem flag exists for the compiler in use)

**Comment by piotrsiupa** [comment]
> > > If you had the normal CPPPATH expansion skip any paths which were in CPPSYSPATH, then you'd still get the files scanned and have them cause rebuilds, and get some of them with -isystem..
> > 
> > 
> > I'm not sure if I get the context of this statement. I've tested what happens if you just add `-isystem` without including the directory to `CPPPATH` and my observation is that the headers are not in the dependency tree in this case.
> 
> Yes. That's the problem. As I understand it you'd add paths via -isystem to avoid the compiler complaining about them, but you do want to know if those files change and that should cause a rebuild.

Well, yes. I do want that I and wrote the code in a way that it will happen. What's the problem then?

**Comment by piotrsiupa** [comment]
> Also you'd want to have the build do something reasonable (like use -I if no equivalent -isystem flag exists for the compiler in use).
> 
> Though this bit would really only apply when we get around to adding this functionality to SCons core.

Currently the code works for GCC Clang and MSVC. Do we have a list of all compilers that SCons is supposed to support? I don't promise I'll spend a lot of time on it but I could add support for the ones that are easy to research and change the code so it doesn't add any `-isystem` like flag for the remaining ones.

**Pull request closed without merging**
